remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
title: [Wordpress CDN]
tagline: [A repo for offloading Wordpress static file]
description: [This project automatically builds and publishes WordPress static core assets, such as CSS, JS, images, fonts, and more, into GitHub Pages for use as a CDN.The goal is to offload front-end assets, like /wp-includes/js/ and /wp-admin/css/, from your VPS or WordPress host. This reduces bandwidth and improves loading speed for visitors around the world.]